[package]
name = "patchelfdd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
elf = "0.7.4"
snafu = "0.8.4"
structopt = "0.3.26"
